//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroidExplorer.Bootstrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroidExplorer.Bootstrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Android Software Development Kit License Agreement.
        ///
        ///1. Introduction
        ///
        ///1.1 The Android Software Development Kit (referred to in this License Agreement as the &quot;SDK&quot; and specifically including the Android system files, packaged APIs, and Google APIs add-ons) is licensed to you subject to the terms of this License Agreement. This License Agreement forms a legally binding contract between you and Google in relation to your use of the SDK.
        ///
        ///1.2 &quot;Google&quot; means Google Inc., a Delaware corporation  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AndroidSdkEULA {
            get {
                return ResourceManager.GetString("AndroidSdkEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} bytes of {1} bytes.
        /// </summary>
        internal static string DownloadInfoFormat {
            get {
                return ResourceManager.GetString("DownloadInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the Platform Tools....
        /// </summary>
        internal static string DownloadingPlatformToolsMessage {
            get {
                return ResourceManager.GetString("DownloadingPlatformToolsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the SDK Tools....
        /// </summary>
        internal static string DownloadingSdkToolsMessage {
            get {
                return ResourceManager.GetString("DownloadingSdkToolsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download tools....
        /// </summary>
        internal static string DownloadPrepMessage {
            get {
                return ResourceManager.GetString("DownloadPrepMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the Android SDK.
        /// </summary>
        internal static string DownloadSDKMessage {
            get {
                return ResourceManager.GetString("DownloadSDKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}....
        /// </summary>
        internal static string ExtractingFileFormat {
            get {
                return ResourceManager.GetString("ExtractingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Platform Tools....
        /// </summary>
        internal static string ExtractingPlatformToolsMessage {
            get {
                return ResourceManager.GetString("ExtractingPlatformToolsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting SDK Tools....
        /// </summary>
        internal static string ExtractingSdkToolsMessage {
            get {
                return ResourceManager.GetString("ExtractingSdkToolsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Repository....
        /// </summary>
        internal static string GetRepositoryMesage {
            get {
                return ResourceManager.GetString("GetRepositoryMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install of Droid Explorer is now complete. Click the Finish button below to exit the Setup Wizard..
        /// </summary>
        internal static string InstallFinishedMessage {
            get {
                return ResourceManager.GetString("InstallFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Completed Successfully.
        /// </summary>
        internal static string InstallFinishedTitle {
            get {
                return ResourceManager.GetString("InstallFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Setup Wizard will install all the necessary components to get Droid Explorer running on your computer. Click Next to continue or Cancel to exit the Setup Wizard..
        /// </summary>
        internal static string InstallStartMessage {
            get {
                return ResourceManager.GetString("InstallStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate install path registry key.
        /// </summary>
        internal static string NoRegistryInstallPathMessage {
            get {
                return ResourceManager.GetString("NoRegistryInstallPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify the specified path as a valid Android SDK directory.
        /// </summary>
        internal static string NotSDKPathMessage {
            get {
                return ResourceManager.GetString("NotSDKPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android SDK Invalid.
        /// </summary>
        internal static string NotSDKPathTitle {
            get {
                return ResourceManager.GetString("NotSDKPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdk:platform/sdk:version[text()=&apos;{0}&apos;]/../sdk:revision[text()=&apos;{1}&apos;]/../sdk:archives/sdk:archive[@os=&apos;windows&apos;].
        /// </summary>
        internal static string PlatformArchiveXPath {
            get {
                return ResourceManager.GetString("PlatformArchiveXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate platform tools url.
        /// </summary>
        internal static string PlatformUrlNotFoundMessage {
            get {
                return ResourceManager.GetString("PlatformUrlNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing SDK Directory....
        /// </summary>
        internal static string PrepSdkPathMessage {
            get {
                return ResourceManager.GetString("PrepSdkPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (407) Proxy Authentication Required.
        /// </summary>
        internal static string ProxyExceptionMessage {
            get {
                return ResourceManager.GetString("ProxyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write sdk path to registry.
        /// </summary>
        internal static string RegistryAccessExceptionMessage {
            get {
                return ResourceManager.GetString("RegistryAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android SDK Path:.
        /// </summary>
        internal static string SDKPathText {
            get {
                return ResourceManager.GetString("SDKPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate sdk tools url.
        /// </summary>
        internal static string SdkUrlNotFoundMessage {
            get {
                return ResourceManager.GetString("SdkUrlNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_background {
            get {
                object obj = ResourceManager.GetObject("security_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAandroid SDK directory for Droid Explorer to use..
        /// </summary>
        internal static string SelectSDKInfoMessage {
            get {
                return ResourceManager.GetString("SelectSDKInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Android SDK root.
        /// </summary>
        internal static string SelectSDKRootTitle {
            get {
                return ResourceManager.GetString("SelectSDKRootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up SDK Path....
        /// </summary>
        internal static string SettingupSdkPathMessage {
            get {
                return ResourceManager.GetString("SettingupSdkPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon setup {
            get {
                object obj = ResourceManager.GetObject("setup", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setup_icon {
            get {
                object obj = ResourceManager.GetObject("setup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up Android SDK for me.
        /// </summary>
        internal static string SetUpSDKMessage {
            get {
                return ResourceManager.GetString("SetUpSDKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdk:tool/sdk:revision[text()=&apos;{0}&apos;]/../sdk:archives/sdk:archive[@os=&apos;windows&apos;].
        /// </summary>
        internal static string ToolsArchiveXPath {
            get {
                return ResourceManager.GetString("ToolsArchiveXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIBanner {
            get {
                object obj = ResourceManager.GetObject("UIBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIDialog {
            get {
                object obj = ResourceManager.GetObject("UIDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal Completed Successfully.
        /// </summary>
        internal static string UninstallFinishedTitle {
            get {
                return ResourceManager.GetString("UninstallFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall of Droid Explorer is now complete. Click the Finish button below to exit the Setup Wizard..
        /// </summary>
        internal static string UninstallFinshedMessage {
            get {
                return ResourceManager.GetString("UninstallFinshedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Setup Wizard will remove all the previously installed components to completely uninstall Droid Explorer from your system. Click the Next button to continue, or the Cancel button to exit..
        /// </summary>
        internal static string UninstallStartMessage {
            get {
                return ResourceManager.GetString("UninstallStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer Bootstrapper ({0}).
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
