//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroidExplorer.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroidExplorer.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div[^&gt;]+id=&quot;apk-appcontainer&quot;\s*&gt;\s*&lt;a[^&gt;]+href=&quot;([^&quot;]+)&quot;[^&gt;]*&gt;.*&lt;/a&gt;\s*&lt;div\s+id=&quot;apk-description&quot;&gt;\s*&lt;span\sclass=&quot;apk-name&quot;&gt;(.*)&lt;/span&gt;\s*&lt;br\s*/&gt;\s*&lt;span\sclass=&quot;apk-description&quot;&gt;(.*?)(?:&lt;/span&gt;)?\s*(?:&lt;span\sclass=&quot;apk-author&quot;&gt;\s*(?:&lt;a[^&gt;]*&gt;)?(.*?)(?:&lt;/a&gt;)?&lt;/span&gt;)?(?:&lt;/span&gt;|&lt;/div&gt;).
        /// </summary>
        public static string AndapkInfoRegexPattern {
            get {
                return ResourceManager.GetString("AndapkInfoRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] androidscreencast {
            get {
                object obj = ResourceManager.GetObject("androidscreencast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;BareBonesBackup&gt;
        ///  &lt;OutputFile&gt;update-gab-{0}-signed.zip&lt;/OutputFile&gt;
        ///  &lt;Files&gt;
        ///    &lt;File&gt;/system/app/BugReport.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/checkin.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/Clicker.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/Gmail.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/GmailProvider.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/GoogleApps.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/GooglePartnerSetup.apk&lt;/File&gt;
        ///    &lt;File&gt;/system/app/GoogleSettingsProvider.apk&lt;/File&gt;
        ///    &lt;File&gt;/system [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BareBonesBackup_config {
            get {
                return ResourceManager.GetString("BareBonesBackup_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bart_sh {
            get {
                object obj = ResourceManager.GetObject("bart_sh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] desktopsmslauncher {
            get {
                object obj = ResourceManager.GetObject("desktopsmslauncher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flash_icon {
            get {
                object obj = ResourceManager.GetObject("flash_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] gab_update_script {
            get {
                object obj = ResourceManager.GetObject("gab_update_script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SignApk_zip {
            get {
                object obj = ResourceManager.GetObject("SignApk_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT type,name,tbl_name,rootpage,sql FROM sqlite_master WHERE type=&apos;index&apos; ORDER BY &apos;name&apos;;.
        /// </summary>
        public static string SqliteGetIndexes {
            get {
                return ResourceManager.GetString("SqliteGetIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT type,name,tbl_name,rootpage,sql FROM sqlite_master WHERE type=&apos;table&apos; ORDER BY &apos;name&apos;;.
        /// </summary>
        public static string SqliteGetTables {
            get {
                return ResourceManager.GetString("SqliteGetTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT type,name,tbl_name,rootpage,sql FROM sqlite_master WHERE type=&apos;trigger&apos; ORDER BY &apos;name&apos;;.
        /// </summary>
        public static string SqliteGetTriggers {
            get {
                return ResourceManager.GetString("SqliteGetTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT type,name,tbl_name,rootpage,sql FROM sqlite_master WHERE type=&apos;view&apos; ORDER BY &apos;name&apos;;.
        /// </summary>
        public static string SqliteGetViews {
            get {
                return ResourceManager.GetString("SqliteGetViews", resourceCulture);
            }
        }
    }
}
