//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroidExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroidExplorer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://play.google.com/store/apps/details?id=eu.chainfire.adbd&amp;hl=en.
        /// </summary>
        public static string AdbdInsecureAppUrl {
            get {
                return ResourceManager.GetString("AdbdInsecureAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://android.stackexchange.com/a/96066/1951.
        /// </summary>
        public static string AdbRootQAUrl {
            get {
                return ResourceManager.GetString("AdbRootQAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer cannot find &apos;{0}&apos;. Check the spelling and try again..
        /// </summary>
        public static string AddressBarPathNotFoundMessage {
            get {
                return ResourceManager.GetString("AddressBarPathNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://de.bit13.com/.
        /// </summary>
        public static string ApplicationWebsiteUrl {
            get {
                return ResourceManager.GetString("ApplicationWebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (root access is disabled|cannot run as root).
        /// </summary>
        public static string CanAdbRootRegex {
            get {
                return ResourceManager.GetString("CanAdbRootRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Directories.
        /// </summary>
        public static string Configuration_PluginDirectoriesHeading {
            get {
                return ResourceManager.GetString("Configuration_PluginDirectoriesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select plugins directory.
        /// </summary>
        public static string Configuration_SelectPluginDirectory {
            get {
                return ResourceManager.GetString("Configuration_SelectPluginDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=8107155.
        /// </summary>
        public static string DontateLink {
            get {
                return ResourceManager.GetString("DontateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to init=(\d{3,})x(\d{3,}).
        /// </summary>
        public static string DumpSysWindowScreenResolutionRegex {
            get {
                return ResourceManager.GetString("DumpSysWindowScreenResolutionRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application|Close Application|Ask for Help|Report Bug.
        /// </summary>
        public static string ErrorUncaughtCommands {
            get {
                return ResourceManager.GetString("ErrorUncaughtCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        public static string ErrorUncaughtMessage {
            get {
                return ResourceManager.GetString("ErrorUncaughtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while running Droid Explorer.
        /// </summary>
        public static string ErrorUncaughtTitle {
            get {
                return ResourceManager.GetString("ErrorUncaughtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while registering Droid Explorer with explorer.
        /// </summary>
        public static string ExtensionRegisterErrorMessage {
            get {
                return ResourceManager.GetString("ExtensionRegisterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during registration.
        /// </summary>
        public static string ExtensionRegisterErrorTitle {
            get {
                return ResourceManager.GetString("ExtensionRegisterErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer has been successfully registered with explorer.
        /// </summary>
        public static string ExtensionRegisterSuccessMessage {
            get {
                return ResourceManager.GetString("ExtensionRegisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer Registered.
        /// </summary>
        public static string ExtensionRegisterSuccessTitle {
            get {
                return ResourceManager.GetString("ExtensionRegisterSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while unregistering Droid Explorer with explorer.
        /// </summary>
        public static string ExtensionUnregisterErrorMessage {
            get {
                return ResourceManager.GetString("ExtensionUnregisterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deregistration.
        /// </summary>
        public static string ExtensionUnregisterErrorTitle {
            get {
                return ResourceManager.GetString("ExtensionUnregisterErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer has been successfully unregistered from explorer.
        /// </summary>
        public static string ExtensionUnregisterSuccessMessage {
            get {
                return ResourceManager.GetString("ExtensionUnregisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer Unregistered.
        /// </summary>
        public static string ExtensionUnregisterSuccessTitle {
            get {
                return ResourceManager.GetString("ExtensionUnregisterSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i &quot;{0}&quot; -vf &quot;{2}&quot; -metadata:s:v rotate=0 -codec:v libx264 -codec:a copy &quot;{1}&quot; -y.
        /// </summary>
        public static string FFMpegRotateArguments {
            get {
                return ResourceManager.GetString("FFMpegRotateArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([^\s]+)\s+(tcp|local|dev|jdwp)\:([^\s]+)\s(localabstract|tcp|local|dev|jdwp)\:([^\s]+)$.
        /// </summary>
        public static string ForwardListRegexPattern {
            get {
                return ResourceManager.GetString("ForwardListRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(localabstract|tcp|local|dev|jdwp)\:(.*?)$.
        /// </summary>
        public static string ForwardTypeRegexPattern {
            get {
                return ResourceManager.GetString("ForwardTypeRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([a-zA-Z0-9][a-zA-Z0-9-_]{0,61}[a-zA-Z0-9]{0,1}\.)+([a-zA-Z]{1,6}|[a-zA-Z0-9-]{1,30}\.[a-zA-Z]{2,3})\:\d{1,}$.
        /// </summary>
        public static string HostDeviceRegex {
            get {
                return ResourceManager.GetString("HostDeviceRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\:\d{1,}$.
        /// </summary>
        public static string IPDeviceRegex {
            get {
                return ResourceManager.GetString("IPDeviceRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://de.codeplex.com/WorkItem/Create.aspx.
        /// </summary>
        public static string IssueTrackerCreateUrl {
            get {
                return ResourceManager.GetString("IssueTrackerCreateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DroidExplorer.DroidExplorer.log4net.
        /// </summary>
        public static string Log4NetDroidExplorer {
            get {
                return ResourceManager.GetString("Log4NetDroidExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not warn me of this in the future..
        /// </summary>
        public static string NoAdbRootCheckboxText {
            get {
                return ResourceManager.GetString("NoAdbRootCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue|Continue and show more information|Get Adbd Insecure and Exit|Exit.
        /// </summary>
        public static string NoAdbRootCommands {
            get {
                return ResourceManager.GetString("NoAdbRootCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to gain root access for ADB. You may have limited access to folders on the device.
        ///
        ///You can use adbd Insecure by Chainfire to allow adb to run as root..
        /// </summary>
        public static string NoAdbRootMessage {
            get {
                return ResourceManager.GetString("NoAdbRootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to gain ADB root access.
        /// </summary>
        public static string NoAdbRootTitle {
            get {
                return ResourceManager.GetString("NoAdbRootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify a version for build tools..
        /// </summary>
        public static string NoBuildToolsMessage {
            get {
                return ResourceManager.GetString("NoBuildToolsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://de.codeplex.com/.
        /// </summary>
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.pushbullet.com/channel?tag=droidexplorerreleases.
        /// </summary>
        public static string Pushbullet_ReleasesUrl {
            get {
                return ResourceManager.GetString("Pushbullet_ReleasesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.pushbullet.com/channel?tag=droidexplorersource.
        /// </summary>
        public static string Pushbullet_SourceCommitUrl {
            get {
                return ResourceManager.GetString("Pushbullet_SourceCommitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the android SDK tools, please reinstall the application..
        /// </summary>
        public static string SdkPathNotFoundMessage {
            get {
                return ResourceManager.GetString("SdkPathNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to device: {0}.
        /// </summary>
        public static string SplashConnectingDevice {
            get {
                return ResourceManager.GetString("SplashConnectingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Attached Devices.
        /// </summary>
        public static string SplashGetDevices {
            get {
                return ResourceManager.GetString("SplashGetDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating Android SDK Tools.
        /// </summary>
        public static string SplashLocatingSdk {
            get {
                return ResourceManager.GetString("SplashLocatingSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Device: {0}.
        /// </summary>
        public static string SplashRegisterDevice {
            get {
                return ResourceManager.GetString("SplashRegisterDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to launch ADB as Root..
        /// </summary>
        public static string SplashRunAdbAsRoot {
            get {
                return ResourceManager.GetString("SplashRunAdbAsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ADB Server.
        /// </summary>
        public static string SplashStartAdb {
            get {
                return ResourceManager.GetString("SplashStartAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://android.stackexchange.com/questions/tagged/droidexplorer.
        /// </summary>
        public static string SupportUrl {
            get {
                return ResourceManager.GetString("SupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droid Explorer: {0}.
        /// </summary>
        public static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} item{2} ({1:fs}).
        /// </summary>
        public static string TransferFormCopyLabel {
            get {
                return ResourceManager.GetString("TransferFormCopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} ({1}) to {2} ({3}).
        /// </summary>
        public static string TransferFormFromLabel {
            get {
                return ResourceManager.GetString("TransferFormFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items remaining: {0}.
        /// </summary>
        public static string TransferFormItemsRemainingLabel {
            get {
                return ResourceManager.GetString("TransferFormItemsRemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining: about {0}.
        /// </summary>
        public static string TransferFormTimeRemainingLabel {
            get {
                return ResourceManager.GetString("TransferFormTimeRemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering File{0}....
        /// </summary>
        public static string TransferFormTitle {
            get {
                return ResourceManager.GetString("TransferFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://twitter.com/abryanconrad.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when attempting to uninstall the package..
        /// </summary>
        public static string UninstallErrorGenericMessage {
            get {
                return ResourceManager.GetString("UninstallErrorGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to uninstall {0}.
        /// </summary>
        public static string UninstallErrorMessage {
            get {
                return ResourceManager.GetString("UninstallErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the package name.
        /// </summary>
        public static string UninstallErrorNoPackageMessage {
            get {
                return ResourceManager.GetString("UninstallErrorNoPackageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.kingoapp.com/root-tutorials/how-to-enable-usb-debugging-mode-on-android.htm.
        /// </summary>
        public static string UsbDebuggingHelpLink {
            get {
                return ResourceManager.GetString("UsbDebuggingHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb.
        /// </summary>
        public static string WifiAdbHelpLink {
            get {
                return ResourceManager.GetString("WifiAdbHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.xda-developers.com/showthread.php?t=558108.
        /// </summary>
        public static string XdaThreadLink {
            get {
                return ResourceManager.GetString("XdaThreadLink", resourceCulture);
            }
        }
    }
}
